// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:592315590022:web:dd36087821067d02cd3807',
    messagingSenderId: '592315590022',
    projectId: 'authbloctest2',
    authDomain: 'authbloctest2.firebaseapp.com',
    storageBucket: 'authbloctest2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:592315590022:android:d0f15829bfd6c8c0cd3807',
    messagingSenderId: '592315590022',
    projectId: 'authbloctest2',
    storageBucket: 'authbloctest2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:592315590022:ios:6426c52ca8102d82cd3807',
    messagingSenderId: '592315590022',
    projectId: 'authbloctest2',
    storageBucket: 'authbloctest2.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:592315590022:ios:c6fa3d07b4d6471dcd3807',
    messagingSenderId: '592315590022',
    projectId: 'authbloctest2',
    storageBucket: 'authbloctest2.appspot.com',
    iosBundleId: 'com.example.practice.RunnerTests',
  );
}
